server:
  port: 8080
  

  
spring:
  redis:
    database: 2
    host: ${redis.host:localhost}
    port: 6379
    password: 29c4181fb842b5f24a3103dbd2ba17accb1f7e3c8f198689821f7955401ab921
    pool:
      max-idle: 300        #数据库链接最大空闲数,超过空闲时间，数据库连接将被标记为不可用，然后被释放。设为0表示无限制。
      max-active: 600      #连接池的最大数据库连接数。设为0表示无限制。
      max-wait:   5000     #最大等待毫秒数, 单位为 ms, 超过时间会出错误信息
      
      
    
front:
  asset-host: localhost:3000
  asset-manifest-url: http://localhost:3000/manifest.json
